name = "eiquekies"
main = "backend/src/index.js"
compatibility_date = "2026-07-31"

# Menghubungkan Folder Frontend PWA
[assets]
directory = "./frontend"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "eiquekies_db"
database_id = "a1b2c3d4-e5f6-7890-abcd-123456789xyz"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "eiquekies_super_secret_jwt_key_2026_cute_bakery"
